- name: Sync releases
  uses: andrewthetechie/gha-clone-releases@v1
  with:
    token: ${{ secrets.PAT }}
    src_repo: blingbling-bow/HugoAura-Enhanced
    copy_assets: true
    include_prerelease: true 
